name: pushJob
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: .NET Core CLI          
        uses: baruchiro/github-actions@0.0.1
      - run: dotnet restore
      - run: dotnet build
