name: pushJob
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baruchiro/github-actions@0.0.1
      - run: dotnet restore
      - run: dotnet build
